version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ticketing_postgres
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: ticketing_redis
    ports:
      - "6379:6379"